# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
FPS = 60
SIDE_PANNEL = 300
HEALTH = 100
MONEY = 650

# Enemy constants
SPAWN_COOLDOWN = 400

# Grid settings
TILE_SIZE = 50  # Size of each tile
GRID_WIDTH = SCREEN_WIDTH // TILE_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // TILE_SIZE

# Turret constsants
TURRET_LEVELS = 2
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 1
ANIMATION_STEPS = 8
ANIMATION_DELAY = 100
DAMAGE = 5